In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.svm import SVR
warnings.filterwarnings('ignore')

In [4]:
data = pd.read_csv("./Video_Games_Sales_as_at_22_Dec_2016.csv")
data.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data = data.rename(columns={"Year_of_Release": "Year", 
                            "NA_Sales": "NA",
                            "EU_Sales": "EU",
                            "JP_Sales": "JP",
                            "Other_Sales": "Other",
                            "Global_Sales": "Global"})
data = data[data["Year"].notnull()]
data = data[data["Genre"].notnull()]
data["Year"] = data["Year"].apply(int)
data["Age"] = 2021 - data["Year"]
data.describe(include="all")

,Name,Platform,Year,Genre,Publisher,NA,EU,JP,Other,Global,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Age
count,16448,16448,16448.000000,16448,16416,16448.000000,16448.000000,16448.000000,16448.000000,16448.00000,7983.000000,7983.000000,9840,7463.000000,9907,9769,16448.000000
unique,11429,31,NaN,12,579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96,NaN,1680,8,NaN
top,Need for Speed: Most Wanted,PS2,NaN,Action,Electronic Arts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tbd,NaN,Ubisoft,E,NaN
freq,12,2127,NaN,3308,1344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2377,NaN,201,3922,NaN
mean,NaN,NaN,2006.488996,NaN,NaN,0.263965,0.145895,0.078472,0.047583,0.53617,68.994363,26.441313,NaN,163.015141,NaN,NaN,14.511004
std,NaN,NaN,5.877470,NaN,NaN,0.818286,0.506660,0.311064,0.187984,1.55846,13.920060,19.008136,NaN,563.863327,NaN,NaN,5.877470
min,NaN,NaN,1980.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.01000,13.000000,3.000000,NaN,4.000000,NaN,NaN,1.000000
25%,NaN,NaN,2003.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.06000,60.000000,12.000000,NaN,10.000000,NaN,NaN,11.000000
50%,NaN,NaN,2007.000000,NaN,NaN,0.080000,0.020000,0.000000,0.010000,0.17000,71.000000,22.000000,NaN,24.000000,NaN,NaN,14.000000
75%,NaN,NaN,2010.000000,NaN,NaN,0.240000,0.110000,0.040000,0.030000,0.47000,79.000000,36.000000,NaN,81.000000,NaN,NaN,18.000000
max,NaN,NaN,2020.000000,NaN,NaN,41.360000,28.960000,10.220000,10.570000,82.53000,98.000000,113.000000,NaN,10665.000000,NaN,NaN,41.000000

In [6]:
data['Global'].count

<bound method Series.count of 0        82.53
1        40.24
2        35.52
3        32.77
4        31.37
         ...
16714     0.01
16715     0.01
16716     0.01
16717     0.01
16718     0.01
Name: Global, Length: 16448, dtype: float64>

In [7]:
global_sales = data['Global'].unique()

In [11]:
global_sales.sort()

In [12]:
global_sales

array([1.000e-02, 2.000e-02, 3.000e-02, 4.000e-02, 5.000e-02, 6.000e-02,
       7.000e-02, 8.000e-02, 9.000e-02, 1.000e-01, 1.100e-01, 1.200e-01,
       1.300e-01, 1.400e-01, 1.500e-01, 1.600e-01, 1.700e-01, 1.800e-01,
       1.900e-01, 2.000e-01, 2.100e-01, 2.200e-01, 2.300e-01, 2.400e-01,
       2.500e-01, 2.600e-01, 2.700e-01, 2.800e-01, 2.900e-01, 3.000e-01,
       3.100e-01, 3.200e-01, 3.300e-01, 3.400e-01, 3.500e-01, 3.600e-01,
       3.700e-01, 3.800e-01, 3.900e-01, 4.000e-01, 4.100e-01, 4.200e-01,
       4.300e-01, 4.400e-01, 4.500e-01, 4.600e-01, 4.700e-01, 4.800e-01,
       4.900e-01, 5.000e-01, 5.100e-01, 5.200e-01, 5.300e-01, 5.400e-01,
       5.500e-01, 5.600e-01, 5.700e-01, 5.800e-01, 5.900e-01, 6.000e-01,
       6.100e-01, 6.200e-01, 6.300e-01, 6.400e-01, 6.500e-01, 6.600e-01,
       6.700e-01, 6.800e-01, 6.900e-01, 7.000e-01, 7.100e-01, 7.200e-01,
       7.300e-01, 7.400e-01, 7.500e-01, 7.600e-01, 7.700e-01, 7.800e-01,
       7.900e-01, 8.000e-01, 8.100e-01, 8.200e-01, 8.300e-01, 8.400e-01,
       8.500e-01, 8.600e-01, 8.700e-01, 8.800e-01, 8.900e-01, 9.000e-01,
       9.100e-01, 9.200e-01, 9.300e-01, 9.400e-01, 9.500e-01, 9.600e-01,
       9.700e-01, 9.800e-01, 9.900e-01, 1.000e+00, 1.010e+00, 1.020e+00,
       1.030e+00, 1.040e+00, 1.050e+00, 1.060e+00, 1.070e+00, 1.080e+00,
       1.090e+00, 1.100e+00, 1.110e+00, 1.120e+00, 1.130e+00, 1.140e+00,
       1.150e+00, 1.160e+00, 1.170e+00, 1.180e+00, 1.190e+00, 1.200e+00,
       1.210e+00, 1.220e+00, 1.230e+00, 1.240e+00, 1.250e+00, 1.260e+00,
       1.270e+00, 1.280e+00, 1.290e+00, 1.300e+00, 1.310e+00, 1.320e+00,
       1.330e+00, 1.340e+00, 1.350e+00, 1.360e+00, 1.370e+00, 1.380e+00,
       1.390e+00, 1.400e+00, 1.410e+00, 1.420e+00, 1.430e+00, 1.440e+00,
       1.450e+00, 1.460e+00, 1.470e+00, 1.480e+00, 1.490e+00, 1.500e+00,
       1.510e+00, 1.520e+00, 1.530e+00, 1.540e+00, 1.550e+00, 1.560e+00,
       1.570e+00, 1.580e+00, 1.590e+00, 1.600e+00, 1.610e+00, 1.620e+00,
       1.630e+00, 1.640e+00, 1.650e+00, 1.660e+00, 1.670e+00, 1.680e+00,
       1.690e+00, 1.700e+00, 1.710e+00, 1.720e+00, 1.730e+00, 1.740e+00,
       1.750e+00, 1.760e+00, 1.770e+00, 1.780e+00, 1.790e+00, 1.800e+00,
       1.810e+00, 1.820e+00, 1.830e+00, 1.840e+00, 1.850e+00, 1.860e+00,
       1.870e+00, 1.880e+00, 1.890e+00, 1.900e+00, 1.910e+00, 1.920e+00,
       1.930e+00, 1.940e+00, 1.950e+00, 1.960e+00, 1.970e+00, 1.980e+00,
       1.990e+00, 2.000e+00, 2.010e+00, 2.020e+00, 2.030e+00, 2.040e+00,
       2.050e+00, 2.060e+00, 2.070e+00, 2.080e+00, 2.090e+00, 2.100e+00,
       2.110e+00, 2.120e+00, 2.130e+00, 2.140e+00, 2.150e+00, 2.160e+00,
       2.170e+00, 2.180e+00, 2.190e+00, 2.200e+00, 2.210e+00, 2.220e+00,
       2.230e+00, 2.240e+00, 2.250e+00, 2.260e+00, 2.270e+00, 2.280e+00,
       2.290e+00, 2.300e+00, 2.310e+00, 2.320e+00, 2.340e+00, 2.350e+00,
       2.360e+00, 2.370e+00, 2.380e+00, 2.390e+00, 2.400e+00, 2.410e+00,
       2.420e+00, 2.430e+00, 2.440e+00, 2.450e+00, 2.460e+00, 2.470e+00,
       2.480e+00, 2.490e+00, 2.500e+00, 2.520e+00, 2.530e+00, 2.540e+00,
       2.560e+00, 2.570e+00, 2.580e+00, 2.590e+00, 2.600e+00, 2.610e+00,
       2.620e+00, 2.630e+00, 2.650e+00, 2.660e+00, 2.670e+00, 2.680e+00,
       2.690e+00, 2.700e+00, 2.710e+00, 2.730e+00, 2.750e+00, 2.760e+00,
       2.770e+00, 2.780e+00, 2.790e+00, 2.800e+00, 2.810e+00, 2.820e+00,
       2.830e+00, 2.840e+00, 2.850e+00, 2.860e+00, 2.870e+00, 2.880e+00,
       2.890e+00, 2.900e+00, 2.910e+00, 2.920e+00, 2.930e+00, 2.940e+00,
       2.950e+00, 2.960e+00, 2.990e+00, 3.000e+00, 3.010e+00, 3.020e+00,
       3.030e+00, 3.040e+00, 3.050e+00, 3.070e+00, 3.080e+00, 3.090e+00,
       3.100e+00, 3.110e+00, 3.120e+00, 3.130e+00, 3.140e+00, 3.150e+00,
       3.170e+00, 3.180e+00, 3.190e+00, 3.200e+00, 3.210e+00, 3.230e+00,
       3.240e+00, 3.250e+00, 3.260e+00, 3.270e+00, 3.280e+00, 3.300e+00,
       3.310e+00, 3.320e+00, 3.330e+00, 3.340e+00, 3.350e+00, 3.360e+00,
       3.370e+00, 3.380e+00, 3.390e+00, 3.400e+00, 3.410e+00, 3.420e+00,
       3.440e+00, 3.450e+00, 3.460e+00, 3.470e+00, 3.480e+00, 3.490e+00,
       3.500e+00, 3.510e+00, 3.520e+00, 3.530e+00, 3.540e+00, 3.560e+00,
       3.580e+00, 3.590e+00, 3.600e+00, 3.610e+00, 3.620e+00, 3.630e+00,
       3.640e+00, 3.650e+00, 3.660e+00, 3.670e+00, 3.700e+00, 3.710e+00,
       3.720e+00, 3.730e+00, 3.740e+00, 3.760e+00, 3.770e+00, 3.790e+00,
       3.800e+00, 3.830e+00, 3.840e+00, 3.850e+00, 3.870e+00, 3.880e+00,
       3.890e+00, 3.900e+00, 3.910e+00, 3.940e+00, 3.950e+00, 3.960e+00,
       3.970e+00, 3.980e+00, 4.010e+00, 4.030e+00, 4.040e+00, 4.050e+00,
       4.060e+00, 4.070e+00, 4.080e+00, 4.090e+00, 4.100e+00, 4.110e+00,
       4.120e+00, 4.140e+00, 4.160e+00, 4.170e+00, 4.180e+00, 4.190e+00,
       4.200e+00, 4.210e+00, 4.220e+00, 4.230e+00, 4.240e+00, 4.270e+00,
       4.280e+00, 4.290e+00, 4.310e+00, 4.320e+00, 4.330e+00, 4.340e+00,
       4.360e+00, 4.370e+00, 4.380e+00, 4.390e+00, 4.410e+00, 4.420e+00,
       4.430e+00, 4.450e+00, 4.460e+00, 4.470e+00, 4.480e+00, 4.490e+00,
       4.500e+00, 4.530e+00, 4.570e+00, 4.590e+00, 4.600e+00, 4.610e+00,
       4.620e+00, 4.630e+00, 4.670e+00, 4.680e+00, 4.700e+00, 4.710e+00,
       4.730e+00, 4.760e+00, 4.790e+00, 4.800e+00, 4.820e+00, 4.840e+00,
       4.850e+00, 4.870e+00, 4.880e+00, 4.910e+00, 4.920e+00, 4.930e+00,
       4.980e+00, 5.000e+00, 5.010e+00, 5.020e+00, 5.030e+00, 5.050e+00,
       5.070e+00, 5.080e+00, 5.090e+00, 5.100e+00, 5.120e+00, 5.130e+00,
       5.140e+00, 5.150e+00, 5.160e+00, 5.190e+00, 5.200e+00, 5.210e+00,
       5.220e+00, 5.230e+00, 5.240e+00, 5.260e+00, 5.270e+00, 5.290e+00,
       5.300e+00, 5.310e+00, 5.330e+00, 5.340e+00, 5.380e+00, 5.390e+00,
       5.420e+00, 5.450e+00, 5.460e+00, 5.470e+00, 5.480e+00, 5.490e+00,
       5.540e+00, 5.550e+00, 5.580e+00, 5.630e+00, 5.640e+00, 5.740e+00,
       5.780e+00, 5.820e+00, 5.870e+00, 5.950e+00, 5.990e+00, 6.030e+00,
       6.050e+00, 6.080e+00, 6.090e+00, 6.190e+00, 6.210e+00, 6.270e+00,
       6.290e+00, 6.300e+00, 6.310e+00, 6.320e+00, 6.340e+00, 6.390e+00,
       6.400e+00, 6.410e+00, 6.430e+00, 6.440e+00, 6.450e+00, 6.470e+00,
       6.490e+00, 6.510e+00, 6.620e+00, 6.650e+00, 6.660e+00, 6.680e+00,
       6.710e+00, 6.740e+00, 6.750e+00, 6.760e+00, 6.820e+00, 6.830e+00,
       6.900e+00, 6.950e+00, 7.070e+00, 7.090e+00, 7.130e+00, 7.140e+00,
       7.150e+00, 7.160e+00, 7.170e+00, 7.200e+00, 7.320e+00, 7.380e+00,
       7.390e+00, 7.460e+00, 7.510e+00, 7.550e+00, 7.580e+00, 7.590e+00,
       7.600e+00, 7.660e+00, 7.690e+00, 7.720e+00, 7.810e+00, 7.860e+00,
       7.980e+00, 7.990e+00, 8.010e+00, 8.050e+00, 8.070e+00, 8.090e+00,
       8.160e+00, 8.270e+00, 8.380e+00, 8.490e+00, 8.570e+00, 8.760e+00,
       8.790e+00, 8.910e+00, 9.160e+00, 9.180e+00, 9.300e+00, 9.310e+00,
       9.360e+00, 9.440e+00, 9.490e+00, 9.710e+00, 9.720e+00, 9.860e+00,
       9.870e+00, 9.900e+00, 1.012e+01, 1.025e+01, 1.030e+01, 1.049e+01,
       1.050e+01, 1.055e+01, 1.060e+01, 1.070e+01, 1.081e+01, 1.095e+01,
       1.101e+01, 1.118e+01, 1.135e+01, 1.166e+01, 1.168e+01, 1.177e+01,
       1.189e+01, 1.212e+01, 1.213e+01, 1.261e+01, 1.263e+01, 1.266e+01,
       1.284e+01, 1.310e+01, 1.332e+01, 1.347e+01, 1.367e+01, 1.379e+01,
       1.460e+01, 1.461e+01, 1.463e+01, 1.464e+01, 1.473e+01, 1.498e+01,
       1.514e+01, 1.529e+01, 1.585e+01, 1.615e+01, 1.627e+01, 1.728e+01,
       1.814e+01, 1.825e+01, 2.015e+01, 2.061e+01, 2.081e+01, 2.104e+01,
       2.179e+01, 2.181e+01, 2.270e+01, 2.310e+01, 2.321e+01, 2.467e+01,
       2.831e+01, 2.832e+01, 2.892e+01, 2.980e+01, 3.026e+01, 3.137e+01,
       3.277e+01, 3.552e+01, 4.024e+01, 8.253e+01])

In [15]:
max(global_sales)

82.53

In [17]:
min(global_sales)

0.01